### ISSUE TITLE
u-boot-menu fork

### ISSUE THREAD

**Issue by CounterPillow** [CounterPillow/quartz64-images#11]
u-boot-menu currently assumes versioned FDT paths. Device trees are mostly kernel version independent though, and for our device tree package, we want to upgrade it independently of the kernel package, as we don't control the kernel package's release cycle.

- [ ] Do a proper fork of u-boot-menu from the salsa Debian source: https://salsa.debian.org/debian/u-boot-menu/
- [ ] Add the package building to the GitHub Actions Workflow
- [ ] Install the package in the images
- [ ] Add package to repository

We could contribute whatever we're doing back upstream so we can keep using the vanilla package.

**Comment by CounterPillow** [comment]
Turns out this isn't needed because the salsa version of u-boot-menu already allows for this.

**Comment by diederikdehaas** [comment]
\o/

**Comment by CounterPillow** [comment]
Turns out they don't quite, their ordering of fallback stuff makes it impossible to use, unless a recent MR is merged

**Comment by diederikdehaas** [comment]
Usually sending a MR should work, but I **know** it will not with the (specific) maintainer of the ``u-boot-menu`` package.
I told you that before and I saw [someone else making the same remark](https://salsa.debian.org/debian/u-boot-menu/-/merge_requests/9#note_337633):
*FWIW, the maintainer prefers patches sent through the BTS, so I'd suggest posting it in the #1019743 thread.*

FTR: afaik it **is** a good maintainer, he just has a problem with (things like) GitHub and GitLab/Salsa. I *think* because of the requirement of a web based GUI (with non-free JavaScript?), but I don't know.  
But patches send through the BTS are not a problem at all.

**Comment by CounterPillow** [comment]
What a pain

**Comment by diederikdehaas** [comment]
I haven't tried it myself yet, but ``git send-email --to=<bugnumber>@bugs.debian.org`` should work?
Shouldn't be too hard for you ;-)
