### ISSUE TITLE
Device Tree Overlay documentation should include specific SOQuartz related detail from the dts file.

### ISSUE THREAD

**Issue by Gerriko** [CounterPillow/quartz64-images#39]
I've just spent days trying to resolve a problem with a GPIO I had defined as an interrupt pin in my custom overlay file, only to discover through the bootup error log that this pin (GPIO4_A3) is allocated to UART7 and UART7 is set active by the Pine SOQuartz dts file.

As such, for the benefit of others, I wanted suggested that in your documentation page (https://plebian.org/running/dt-overlays/) you provide a reference to this file (and note its importance) as there are plenty of comments within noting where the SOQuartz board deviates from the standard rk2566 and rk356x dtsi files: 
https://kernel.googlesource.com/pub/scm/linux/kernel/git/thierry.reding/linux-pwm/+/for-next/arch/arm64/boot/dts/rockchip/rk3566-soquartz-cm4.dts

**Comment by adminy** [comment]
I wonder since soquartz is using pi io boards, would it be possible to do a low level remapping so all the pi libraries transfer over to soquartz without any extra work for the gpio pins.

**Comment by CounterPillow** [comment]
There appears to be some confusion here. The SOQuartz does not "deviate from the standard rk2566[sic] and rk356x dtsi files", the device tree you use with your board includes those files and applies its own modifications on top. There needs to be no mention of this in any Plebian-specific documentation because it's simply how mainline device trees work; you're not using the rk356x dtsi directly, you're using a tree that includes it. Your confusion comes from your own misunderstanding. The repo you link is a random person's branch for development and not the canonical URL for that file.

Furthermore, I'm getting a bit tired of answering endless questions about basic mainline Linux usage from a company who you work for that promised me payment in private and then never followed up on it. If you want to hire me as a consultant, please have your CEO contact me in private, my rates are very reasonable. Your question(s) have nothing to do with Plebian, and more with how to use embedded mainline Linux in general.

**Comment by adminy** [comment]
Alright, you're hired 😂

**Comment by Gerriko** [comment]
Apologies, no criticism intended and comment/suggestion was merely for the
benefit of others, who also would be on the learning curve and might be
struggling with similar issues. In fact as documentation goes, I personally
have found your website to be the most helpful. So thanks for the work put
in. As with any distro there is always a grey area between what is
considered a Linux issue versus something specific that relates to plebian.
Your overall help in previous matters has been greatly appreciated.
